### ISSUE TITLE
Executable segfaults when ran from outside your work directory

### ISSUE THREAD

**Issue by pde-bakk** [DutChen18/42-cluster#2]
![image](https://user-images.githubusercontent.com/36886300/158182093-f220aa62-47eb-4686-9f1a-77e693772f63.png)

**Comment by DutChen18** [comment]
resolved by https://github.com/DutChen18/42-cluster/commit/e73f5e8584b41940d5c894d246aae62dca4f77a1 and https://github.com/DutChen18/42-cluster/commit/1dcd13a7c107159e06e7e404c37e5a6729abc0fd
